### PR TITLE
update reimbursement message in invite

### PR DESCRIPTION
**Pull request by casassg**
Just a text change on the invite message

### CODE REVIEW

**Review by wailingtam — APPROVED** [review]
I might add a `If you can't attend, please cancel your application invite so we can offer your spot to another hacker. Thanks!`

**Comment by MarceColl** [comment]
lgtm 👍

**Comment by MarceColl** [comment]
What wailing said is a possible good improvement too, yes.

**Comment by casassg** [comment]
Added that @wailingtam @MarceColl

**Comment by victorpm5** [comment]
LGTM, Maybe _"Hope to see you in Barcelona"_ instead of _"Hope you can still make it"_. But looks good anyway.

**Comment by casassg** [comment]
Updated @victorpm5 I like it better too.

**Comment by faix** [comment]
After the changes mentioned, i'm fine with the text.

**Pull request merged**
