### PR TITLE
WIP: Add all features for user interface

### PR DESCRIPTION
**Pull request by casassg**
I needed a canvas to experiment with all the features together. This is it. Not ready or production ready.

Includes PR #92 #93 #95

### CODE REVIEW

**Comment by wailingtam** [comment]
User cases I've tested and works:
- [x] Sign up
- [x] Login
- [x] Verification of email
- [x] Fill in profile info
- [x] Fill in typeform application
- [x] Change password (Tried inserting wrong current password and different new passwords)
- [x] Add and activate 2nd email
- [x] Switch primary email address
- [x] Tried to remove primary email address (not allowed)
- [x] Remove non-primary email address
- [x] Sign out
- [x] Forgot password (tested login with old password after asking for a new password but not resetting it)

**Comment by wailingtam** [comment]
Stuff I've noticed without diggin into the code (I know that this is WIP):
- Should nav back to profile after filling up the typeform application
- **Apply** isn’t marked as `True` after finishing the form (is it what this
message "It may take a little bit to synchronize information..." means?  If so, bad UX)
- The re-send button is available when email has already been verified
- Deactivate apply button if user has already applied
- Add cancel button to cancel sign out
- Add contact@hackupc.com to forgot password contact message

**Comment by casassg** [comment]
Regarding Apply. There's a bit of a problem. I'm using Typeform for application. Is nice but we need to pull data asyncronously. This is the cause for it to show the form even if you finished. This won't happen in production as I will have typeform download every 2/5 minutes.

Regarding the redirect after apply, I can't find a way to make Typeform do it. Any suggestions are welcome, I agree it doesn't look nice but I don't have any alternatives yet -.-

**Comment by casassg** [comment]
> The re-send button is available when email has already been verified

That's default template from AllAuth. I don't see any reason to make it something we need to work on the upcoming future. Rly low-priority.

**Comment by ofpau** [comment]
Tested the staff side (for voting and such).

- [x] Signed up with my `@hackupc.com ` email and permission was given automatically to vote and see the ranking.
- [x] Vote @casassg's application (10/10 would insta-accept)
- [x] Voting and ranking worked as expected
- [x] Account related settings worked as expected: password change, add secondary email address, confirm it, use it to log in, make it primary, try to delete it (not allowed because it was set as primary), make the original address primary, delete the secondary one (allowed now).

The text in the address confirmation email sounds a bit weird to me. More details on slack.

**Comment by casassg** [comment]
Merging to master to enforce branch workflow and to mark this release as stable

**Pull request merged**
