### PR TITLE
Command to add hackers with reimbursement to mail list

### PR DESCRIPTION
**Pull request by ofpau**
Implements #51. As we start allotting travel reimbursement to hackers, this command will be run to add them to a sendgrid mail list to contact them easily (e.g. to request plane tickets)

### CODE REVIEW

**Comment by rgascons** [comment]
why there's a Merge Branch in there

**Comment by ofpau** [comment]
is it wrong? let me know if I should rebase and why

**Comment by rgascons** [comment]
PRs are useful for avoiding extra merges. I would try to avoid them as much as possible.

**Comment by rgascons** [comment]
.. as they pollute the master log.

**Comment by casassg** [comment]
Rebase > Merge ( @dasilvacontin told me once too)

**Review by casassg — APPROVED** [review]
lgtm

**Comment by casassg** [comment]
Make sure next time to use rebase instead @ofpau

**Pull request merged**
