### PR TITLE
Add team registration

### LINKED ISSUE #159: Add Team Applications
## Is this a BUG REPORT or FEATURE REQUEST?

FEATURE REQUEST

Add teams as a new model and allow for team creation and team joining. 

- [ ] Create a team when application created
- [ ] Join a team when application created
- [ ] Send team invites tables for directors
- [ ] Invite teammates if team is invited automatically with signals

### PR DESCRIPTION
**Pull request by casassg**
## What this PR does / Why we need it
Allows user to create/join/leave teams. Missing admin interface for showing applications grouped by teams (to invite) + add teammates in hacker detail view.

## Which issue(s) this PR fixes (optional) 

Fixes #159 

## Some questions
- [x] I have read the contributing guidelines
- [x] I abide by this repository Code of Conduct
- [x] I understand that my PR won't be merged until Travis gives a "green light"

### CODE REVIEW

**Comment by AparaV** [comment]
I think this looks really good and I'm approving it! Meanwhile, I have a few questions:

1. **Can we make the team mates see who else in on the team even if they haven't completed their application?**
image

2. **Do the admins have access to team lists i.e., is there any way they can factor this into the selection process?** I tried it with a sample team, but looks like I have missed it -- I didn't notice anything about teams when I was evaluating their applications.

3. **What do you think about allowing teams to see who on their team got accepted?** I think that hackathon organizers shouldn't reveal that information, but I feel that teams would want to know the status of their teammates' applications.

**Review by AparaV — APPROVED** [review]

**Comment by casassg** [comment]
1. I tried this as it's similar to hackmit/quill. But we can surely add the names. We just need to make sure they understand their application is ready to do or not. I think I may have an idea for that.

2. It's not implemented yet. I was planning on doing a similar tab than invite, but for teams. Then admin can invite a full time at the same time. Also, add the names in the detail view.

3. Not sure about showing acceptance. We can discuss it further, but I'm not convinced.

**Comment by casassg** [comment]
@AparaV Added the admin stuff you asked for and then also added a better way to visualize teammates and teammates missing their application!

Admin view:
screen shot 2017-12-23 at 20 19 29

Update team view:
screen shot 2017-12-23 at 20 17 22

**Comment by AparaV** [comment]
This is amazing 👌 Ready to 🚢 ?

**Pull request merged**
