### PR TITLE
Setup Travis, add python style checker and fix style errors. Closes #88

### LINKED ISSUE #88: Add Travis integration to check code and style
Same as frontend project

### PR DESCRIPTION
**Pull request by wailingtam**
@hackupc/dev I suggest y'all set up the max chars per line config to 79 to follow the PEP 8 style rules.
In PyCharm it's at `Preferences > Editor > Code Style > Right margin (columns): 79`.

Also I'd activate inspections for warnings when violating PEP 8 coding rules (if not already) at:
`Preferences > Editor > Inspections > PEP 8 coding style violation and PEP 8 naming convention violations`.

I've fixed a couple hundreds of style errors that were in the project (because I'm nice 😇 but won't do it twice). From now on, please pay attention to your IDE/editor's warnings ⚠️ and run `pep8 */*.py --exclude="*/migrations,app/settings.py"` (**pip install -r requirements** to install pep8) before pushing anything or just let Travis run it for you and fail ❌.

Will test that Travis works correctly once @casassg enables it for the repo.

Lastly, I'm not sure where to put the command in the README, so if someone can add it to the right place I'd be forever grateful.

### CODE REVIEW

**Comment by casassg** [comment]
@wailingtam added Travis to README and triggered first build

**Comment by casassg** [comment]
Increase size for lines also. I like more following Django coding style for this instead of PEP8. They allow 119 characters as this is the width of GitHub code review.

https://docs.djangoproject.com/en/dev/internals/contributing/writing-code/coding-style/

**Comment by wailingtam** [comment]
Sad, PEP8 is the go-to python style guide but I understand ☹️
LGTM but can't approve my own PR

**Comment by casassg** [comment]
I know its the go-to python style, but the char limit makes no sense to me. I rather follow the django coding style because its also a Github maintained project and its the base for our backend.

**Pull request merged**
